

export const cuisines = [
    { id: 1, name: "Asian" },
    { id: 2, name: "Italian" },
    { id: 3, name: "Mexican" },
    { id: 4, name: "Indian" },
    { id: 5, name: "Thai" },
    { id: 6, name: "Japanese" },
    { id: 7, name: "Chinese" },
    { id: 8, name: "French" },
    { id: 9, name: "Greek" },
    { id: 10, name: "Lebanese" },
    { id: 11, name: "American" },
    { id: 12, name: "Spanish" },
    { id: 13, name: "Vietnamese" },
    { id: 14, name: "Turkish" },
    { id: 15, name: "Korean" },
    { id: 16, name: "Brazilian" },
    { id: 17, name: "German" },
    { id: 18, name: "Moroccan" },
    { id: 19, name: "Ethiopian" },
    { id: 20, name: "Caribbean" },
    { id: 21, name: "Filipino" },
    { id: 22, name: "Russian" },
    { id: 23, name: "Polish" },
    { id: 24, name: "Peruvian" },
    { id: 25, name: "African" },
    { id: 26, name: "Portuguese" },
    { id: 27, name: "Swedish" },
    { id: 28, name: "Danish" },
    { id: 29, name: "Norwegian" },
    { id: 30, name: "Finnish" },
    { id: 31, name: "Argentinian" },
    { id: 32, name: "Middle Eastern" },
    { id: 33, name: "Pakistani" },
  ];
  
  export const filters = [
    { id: 1, name: "Gluten-Free" },
    { id: 2, name: "Keto" },
    { id: 3, name: "High-Protein" },
    { id: 4, name: "Low-Calorie" },
    { id: 5, name: "Vegetarian" },
    { id: 6, name: "Vegan" },
    { id: 7, name: "Dairy-Free" },
    { id: 8, name: "Nut-Free" },
    { id: 9, name: "Sugar-Free" },
    { id: 10, name: "Paleo" },
    { id: 11, name: "Low-Carb" },
    { id: 12, name: "Diabetic-Friendly" },
    { id: 13, name: "Whole30" },
    { id: 14, name: "Halal" },
    { id: 15, name: "Kosher" },
    { id: 16, name: "Fodmap-Friendly" },
    { id: 17, name: "Soy-Free" },
    { id: 18, name: "Wheat-Free" },
    { id: 19, name: "Low-Fat" },
    { id: 20, name: "Heart-Healthy" },
  ];
  